### ISSUE TITLE
Get errors when run tempturature control example

### ISSUE THREAD

**Issue by vinhlh** [aws/aws-iot-device-sdk-js#12]
```javascript
Error: Error: write EPROTO
    at MqttClient.<anonymous> (/Users/vinhlh/Works/demeter.vn/aws/aws-iot-device-sdk-js/device/index.js:68:15)
    at emitOne (events.js:82:20)
    at MqttClient.emit (events.js:169:7)
    at TLSSocket.handleTLSerrors (/Users/vinhlh/Works/demeter.vn/aws/aws-iot-device-sdk-js/node_modules/mqtt/lib/connect/tls.js:39:18)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
```

**Comment by vinhlh** [comment]
I just forgot to set the region.
