### ISSUE TITLE
Error: Error: write EPROTO

### ISSUE THREAD

**Issue by anujdeshpande** [aws/aws-iot-device-sdk-js#15]
I am trying to run the examples, and i get the following error 

```
➜  examples git:(master) ✗ node device-example.js -k private.pem.key -c certificate.pem.crt -a VeriSign-Class\ 3-Public-Primary-Certification-Authority-G5.pem.txt
/Users/anuj/projects/aws-iot-device-sdk-js/device/index.js:68
        throw new Error(error);
        ^

Error: Error: write EPROTO
    at MqttClient.<anonymous> (/Users/anuj/projects/aws-iot-device-sdk-js/device/index.js:68:15)
    at emitOne (events.js:82:20)
    at MqttClient.emit (events.js:169:7)
    at TLSSocket.handleTLSerrors (/Users/anuj/projects/aws-iot-device-sdk-js/node_modules/mqtt/lib/connect/tls.js:39:18)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at onwriteError (_stream_writable.js:304:10)
    at onwrite (_stream_writable.js:322:5)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at fireErrorCallbacks (net.js:442:13)
```

**Comment by gkwicker** [comment]
Hi Anuj,

I'm sorry the example programs aren't working for you; do you know what region you created the certificate in?  By default, the example programs will use 'us-east-1'.  If you created your client certificate and private key in another region (e.g. 'us-west-2'), the example program will not be able to connect unless you specify the region name as one of the command line parameters.  The example programs use the '-g' flag to specify a different region name, e.g. '-g us-west-2'.  Can you check what region your certificate and private key were created in and make sure that the example program is using the right region?  We'll leave this issue open until we find the source of the problem; let us know if you can fix the issue by specifying a different region.

**Comment by anujdeshpande** [comment]
@gkwicker Thanks ! It worked !
Also, it'll be handy to have this instruction in the [Readme](https://github.com/aws/aws-iot-device-sdk-js/blob/master/README.md#example-programs)
