### ISSUE TITLE
Using own CA : unable to get local issuer certificate

### ISSUE THREAD

**Issue by xtrycatchx** [aws/aws-iot-device-sdk-js#156]
I encountered the error upon connecting to AWS IoT over MQTT using my own CA certificate and my own Device Private Key and Device Certificate:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: unable to get local issuer certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:628:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38)
```
The code that attempt to connect is
```
var awsIot = require('aws-iot-device-sdk');
var device = awsIot.device({
    keyPath: 'deviceCert.key',
    certPath: 'deviceCert.pem',
    caPath: 'rootCA.pem',
    clientId: 'X509_TEST',
    region: 'ap-southeast-1',
    host: 'xxxxxxxxxxxxx.iot.ap-southeast-x.amazonaws.com'
});
device.on('connect', function () {
    console.log('Yey');
});
device.on('message', function (mqttTopic, payload) {
    console.log('message', mqttTopic, payload.toString());
});
device.subscribe(['TEST_TOPIC']);
```
How i generated the rootCA
```
openssl genrsa -out rootCA.key 2048
openssl req -x509 -new -nodes -key rootCA.key -sha256 -days 1024 -out rootCA.pem
```
How i registered my rootCA
```
openssl genrsa -out verificationCert.key 2048
openssl req -new -key verificationCert.key -out verificationCert.csr
//common name applied was the correct registration code from AWS IoT

openssl x509 -req -in verificationCert.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out verificationCert.pem -days 500 -sha256

aws iot register-ca-certificate --ca-certificate file://rootCA.pem --verification-cert file://verificationCert.pem  
aws iot update-ca-certificate --certificate-id xxxxxxxxxxx --new-status ACTIVE
```

How i create and signed my device cert
```
openssl genrsa -out deviceCert.key 2048
openssl req -new -key deviceCert.key -out deviceCert.csr
openssl x509 -req -in deviceCert.csr -CA rootCA.pem -CAkey rootCA.key -CAcreateserial -out deviceCert.pem -days 500 -sha256
```

I'm quite not sure what did I missed that it resulted to exception mentioned above.
Thanks guys in advance

**Comment by fengsongAWS** [comment]
Hi @xtrycatchx ,
From what I can see from your description, you always need to use AWS IoT rootCA when you try to connect to AWS IoT. 
I think following docs will help you go through the process.
http://docs.aws.amazon.com/iot/latest/developerguide/device-certs-your-own.html
https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot/

**Comment by xtrycatchx** [comment]
Thanks @fengsongAWS . I assume this means the Device would use the AWS CA cert while/and Server(AWS IoT endpoint) would use Device's cert to establish the TLS before MQTT before them.
If yes, we can close this :)
