### ISSUE TITLE
error: exceptions.INVALID_CONNECT_OPTIONS

### ISSUE THREAD

**Issue by polyren** [aws/aws-iot-device-sdk-js#162]
Hi, I'm a new man who is studying aws iot, I followed the guide of how to use raspberry pi connect to iot, but facing this error that I can not figure it out. can anyone helo me with this?
pi@rendupi:~/deviceSDK/node_modules/aws-iot-device-sdk $ sudo node examples/thing-example.js -f ~/deviceSDK/certs
/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/device/index.js:406
      throw new Error(exceptions.INVALID_CONNECT_OPTIONS);
      ^

Error: Invalid connect options supplied.
    at new DeviceClient (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/device/index.js:406:13)
    at Function.DeviceClient (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/device/index.js:201:14)
    at new ThingShadowsClient (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/thing/index.js:123:30)
    at ThingShadowsClient (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/thing/index.js:89:14)
    at processTest (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/examples/thing-example.js:42:25)
    at module.exports (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/examples/lib/cmdline.js:208:4)
    at Object.<anonymous> (/home/pi/deviceSDK/node_modules/aws-iot-device-sdk/examples/thing-example.js:245:4)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)

**Comment by fengsongAWS** [comment]
Did you provide `-H` endpoint option?

**Comment by polyren** [comment]
I just made my own project which runs the basic function of using the data from IOT shadow.
I will close this question.
However, I still want to suggest the amazon WAS to make a clear guide for beginners, like "use the examples you like", there are so many files are named as "examples", but only a few of them are good to run. Also, they need to install other modules, I was so stressful to follow the guidelines of IoT device SDK, hope you can have a more new-man friendly one.
