### ISSUE TITLE
Invalid connect options supplied

### ISSUE THREAD

**Issue by milanvadher** [aws/aws-iot-device-sdk-js#200]
Error: Invalid connect options supplied.
    at new DeviceClient (http://localhost:8100/build/vendor.js:64939:19)
    at Object.312 (http://localhost:8100/build/main.js:303:14)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.261 (http://localhost:8100/build/main.js:151:85)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.239 (http://localhost:8100/build/main.js:131:70)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1

I am not able to connect using ionic 3 

SOS
newbie here....
help help

**Comment by fengsongAWS** [comment]
This means you have some required parameters not provided such as key, cert or IAM credentials. Please look into example and see if you are running them successfully.

**Comment by fengsongAWS** [comment]
Please reopen this issue if you still have problems.

**Comment by ycy88** [comment]
For anyone who reads this, I got this error while porting over code that worked previously on Version 1 of the SDK. From version 2.x.x onwards you need to pass in a "host" property under your connect options.
