### ISSUE TITLE
 job-examples.js not working 

### ISSUE THREAD

**Issue by thecloudslayer** [aws/aws-iot-device-sdk-js#225]
I'm having issues running job-example.js i keep getting. 

const jobsModule = require('..').jobs;

Error: Cannot find module '..'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/taylor/repo/chm/desktop/test-job.js:21:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

I noticed in your unit tests you use the '../' and that still did not work.

**Comment by AWSSteveHa** [comment]
@thecloudslayer Did you by chance copy the jobs-example.js file to a different location before you ran it? That could cause the error you're seeing.

**Comment by thecloudslayer** [comment]
I'll poke it soon and let you know. Do you know of any more doc on running and setting up jobs?

**Comment by AWSSteveHa** [comment]
@thecloudslayer I recommend following the tutorial in this blog post https://aws.amazon.com/blogs/iot/using-device-jobs-for-over-the-air-updates/

**Comment by AWSSteveHa** [comment]
Closing issue. @thecloudslayer feel free to open a new issue if you are still encountering errors.
