### ISSUE TITLE
Cannot get simple AWS web socket publish to work

### ISSUE THREAD

**Issue by Khalian** [aws/aws-iot-device-sdk-js#231]
I wrote this uber simple client to publish a message to aws sdk via websocket protocol (javascript version). https://github.com/aws/aws-iot-device-sdk-js

```
var awsIot = require('aws-iot-device-sdk');

var device = awsIot.device({
    region: "us-west-2",
    protocol: "wss",
    clientId: "ARUNAVS SUPER TEST",
    host: "iot.us-west-2.amazonaws.com",
    port: "443"
});

device
  .on('connect', function() {
    console.log('connect');
    device.publish('abcd', JSON.stringify({ test_data: 1}));
  });

device
    .on('message', function(topic, payload) {
    console.log('message', topic, payload.toString());
  });

device
  .on('error', function(error) {
     console.log('error', error);
  });
```
I am getting the following error (after importing admin creds https://github.com/aws/aws-iot-device-sdk-js#websockets) a whole bunch of times:-

```
node testCode.js
error { Error: unexpected server response (403)
    at ClientRequest._req.on (/Users/arunavs/mrtests/node_modules/ws/lib/WebSocket.js:653:21)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at TLSSocket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at TLSSocket.Readable.push (_stream_readable.js:135:10)
  type: 'error',
  target:
   WebSocket {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     readyState: 3,
     bytesReceived: 0,
     extensions: null,
     protocol: '',
     _binaryType: 'arraybuffer',
     _finalize: [Function: bound finalize],
     _closeFrameReceived: false,
     _closeFrameSent: false,
     _closeMessage: '',
     _closeTimer: null,
     _finalized: true,

```

The SDK fails to give any reason why I am getting a 403. Any tips?

Note : The SDK examples section would help a lot if it gave simple, ready to use examples like this upfront.

**Comment by Khalian** [comment]
The SDK seems to be pre signing the URLs with Sigv4 correclty. 

     url: 'wss://a1s3zhmqnep3o1.iot.us-west-2.amazonaws.com:443/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential= .......

**Comment by fengsongAWS** [comment]
Hi @Khalian ,
We had some examples in the example directory, did you test the example with your credentials?
What policy did you attach to your role or user?

**Comment by Khalian** [comment]
Running the example had the following error. 

```
node ./examples/device-example.js --protocol=wss --test-mode=1 -H a1s3zhmqnep3o2.iot.us-west-2.amazonaws.com                                                                                                                                                                                                                                                                  1 ↵
connect
```

seems to be working different . Just stuck at 


Credentials used had the following inline policies

    ```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": "*"
        }
    ]
}
```

and 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "*",
            "Resource": "*"
        }
    ]
}
```

**Comment by Khalian** [comment]
Interesting, I just retried my example and the 403 went away.
