### ISSUE TITLE
Takes 21 minutes to ETIMEDOUT and then reconnect

### ISSUE THREAD

**Issue by dushyantbangal** [aws/aws-iot-device-sdk-js#264]
**Scenario:**
I have 2 publishes with `qos:1` every minute. All settings for `device` are.
I'm using a raspberry pi 3 with USB GSM module for internet.
Periodically, I'm resetting the GSM module, and it reconnects to the internet within a few seconds.

**Issue:**

However, `aws-iot-device-sdk` takes around 20-21 minutes to realize that the connection was lost, and it will have to `reconnect`.

About 20-21 minutes after resetting, it throws 
`offline`
then `error` with code `ETIMEDOUT`
then `close`
then `reconnect`
then `connect`, after which it publishes everything in backlog successfully.

**Logs:**
I'm logging `Uploading...` before my `device.publish` and `Uploaded` in its callback. I'm also logging the all events from `device.on()`

You'll see after the connection reset, it doesn't print `Uploaded` until `reconnect`.
```

Mar 12 17:58:24 : debug: Uploading...
Mar 12 17:58:24 : debug: packetsend
Mar 12 17:58:24 : debug: Uploaded
Mar 12 17:58:36 : debug: Uploading...
Mar 12 17:58:36 : debug: packetsend
Mar 12 17:58:36 : debug: Uploaded
Mar 12 17:59:24 : debug: Uploading...
Mar 12 17:59:24 : debug: packetsend
Mar 12 17:59:24 : debug: Uploaded
Mar 12 17:59:36 : debug: Uploading...
Mar 12 17:59:36 : debug: packetsend
Mar 12 17:59:36 : debug: Uploaded

//CONNECTION RESET HERE

Mar 12 18:00:24 : debug: Uploading...
Mar 12 18:00:24 : debug: packetsend
Mar 12 18:00:36 : debug: Uploading...
Mar 12 18:00:36 : debug: packetsend
Mar 12 18:01:24 : debug: Uploading...
Mar 12 18:01:24 : debug: packetsend
Mar 12 18:01:36 : debug: Uploading...
Mar 12 18:01:36 : debug: packetsend
Mar 12 18:02:24 : debug: Uploading...
Mar 12 18:02:24 : debug: packetsend
Mar 12 18:02:36 : debug: Uploading...
Mar 12 18:02:36 : debug: packetsend
Mar 12 18:03:24 : debug: Uploading...
Mar 12 18:03:24 : debug: packetsend
Mar 12 18:03:36 : debug: Uploading...
Mar 12 18:03:36 : debug: packetsend
Mar 12 18:04:24 : debug: Uploading...
Mar 12 18:04:24 : debug: packetsend
Mar 12 18:04:36 : debug: Uploading...
Mar 12 18:04:36 : debug: packetsend
Mar 12 18:05:24 : debug: Uploading...
Mar 12 18:05:24 : debug: packetsend
Mar 12 18:05:36 : debug: Uploading...
Mar 12 18:05:36 : debug: packetsend
Mar 12 18:06:24 : debug: Uploading...
Mar 12 18:06:24 : debug: packetsend
Mar 12 18:06:36 : debug: Uploading...
Mar 12 18:06:36 : debug: packetsend
Mar 12 18:07:24 : debug: Uploading...
Mar 12 18:07:24 : debug: packetsend
Mar 12 18:07:36 : debug: Uploading...
Mar 12 18:07:36 : debug: packetsend
Mar 12 18:08:24 : debug: Uploading...
Mar 12 18:08:24 : debug: packetsend
Mar 12 18:08:36 : debug: Uploading...
Mar 12 18:08:36 : debug: packetsend
Mar 12 18:09:24 : debug: Uploading...
Mar 12 18:09:24 : debug: packetsend
Mar 12 18:09:36 : debug: Uploading...
Mar 12 18:09:36 : debug: packetsend
Mar 12 18:10:24 : debug: Uploading...
Mar 12 18:10:24 : debug: packetsend
Mar 12 18:10:36 : debug: Uploading...
Mar 12 18:10:36 : debug: packetsend
Mar 12 18:11:24 : debug: Uploading...
Mar 12 18:11:24 : debug: packetsend
Mar 12 18:11:36 : debug: Uploading...
Mar 12 18:11:36 : debug: packetsend
Mar 12 18:12:24 : debug: Uploading...
Mar 12 18:12:24 : debug: packetsend
Mar 12 18:12:36 : debug: Uploading...
Mar 12 18:12:36 : debug: packetsend
Mar 12 18:13:24 : debug: Uploading...
Mar 12 18:13:24 : debug: packetsend
Mar 12 18:13:36 : debug: Uploading...
Mar 12 18:13:36 : debug: packetsend
Mar 12 18:14:24 : debug: Uploading...
Mar 12 18:14:24 : debug: packetsend
Mar 12 18:14:36 : debug: Uploading...
Mar 12 18:14:36 : debug: packetsend
Mar 12 18:15:24 : debug: Uploading...
Mar 12 18:15:24 : debug: packetsend
Mar 12 18:15:37 : debug: Uploading...
Mar 12 18:15:37 : debug: packetsend
Mar 12 18:16:24 : debug: Uploading...
Mar 12 18:16:24 : debug: packetsend
Mar 12 18:16:37 : debug: Uploading...
Mar 12 18:16:37 : debug: packetsend
Mar 12 18:17:25 : debug: Uploading...
Mar 12 18:17:25 : debug: packetsend
Mar 12 18:17:37 : debug: Uploading...
Mar 12 18:17:37 : debug: packetsend
Mar 12 18:18:25 : debug: Uploading...
Mar 12 18:18:25 : debug: packetsend
Mar 12 18:18:37 : debug: Uploading...
Mar 12 18:18:37 : debug: packetsend
Mar 12 18:19:25 : debug: Uploading...
Mar 12 18:19:25 : debug: packetsend
Mar 12 18:19:37 : debug: Uploading...
Mar 12 18:19:37 : debug: packetsend
Mar 12 18:20:25 : debug: Uploading...
Mar 12 18:20:25 : debug: packetsend
Mar 12 18:20:37 : debug: Uploading...
Mar 12 18:20:37 : debug: packetsend
Mar 12 18:21:25 : debug: Uploading...
Mar 12 18:21:25 : debug: packetsend
Mar 12 18:21:31 : error: offline
Mar 12 18:21:31 : error: undefined
Mar 12 18:21:31 : undefined
Mar 12 18:21:31 : error: undefined {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"read"}
Mar 12 18:21:31 : { Error: read ETIMEDOUT
Mar 12 18:21:31 :     at _errnoException (util.js:992:11)
Mar 12 18:21:31 :     at TLSWrap.onread (net.js:618:25)
Mar 12 18:21:31 :   code: 'ETIMEDOUT',
Mar 12 18:21:31 :   errno: 'ETIMEDOUT',
Mar 12 18:21:31 :   syscall: 'read',
Mar 12 18:21:31 :   level: 'error',
Mar 12 18:21:31 :   [Symbol(level)]: 'error',
Mar 12 18:21:31 :   [Symbol(message)]: '{"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"read","level":"error"}' }
Mar 12 18:21:31 : error: close
Mar 12 18:21:31 : error: undefined
Mar 12 18:21:31 : undefined
Mar 12 18:21:32 : debug: reconnect
Mar 12 18:21:32 : debug: packetsend
Mar 12 18:21:32 : info: AWS Connected
Mar 12 18:21:32 : debug: packetsend
Mar 12 18:21:32 : debug: packetsend
Mar 12 18:21:33 : debug: Uploaded
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: Uploaded
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: Uploaded
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: Uploaded
Mar 12 18:21:33 : debug: packetsend
Mar 12 18:21:33 : debug: Uploaded
```

Should I be setting something in `device` to make the `aws-iot-device-sdk` detect the connection break sooner and `reconnect`?

**Comment by justinboswell** [comment]
You will want to set the MQTT keepalive value lower to detect the connection failure, it will guarantee that a PINGREQ is sent often enough to detect that the connection died, otherwise you are relying on TCP timeout, which can take forever. You can set it down to 10-20 seconds or so and see if that gets you what you want. The default keepalive is 30 minutes.

**Comment by mevlutsahinn** [comment]
Same issue here. I have a keepAlive value of 90 seconds but still the sdk does not realize the connection is gone.

**Comment by matiasdecarli** [comment]
Are you guys using Docker? I had a similar experience when running my app inside a Docker container with default network config (on a separate network). My issues disappeared when I changed to `network:host`

[Here's](https://github.com/mqttjs/MQTT.js/issues/851) the description & the solution of my issue

**Comment by ydvsailendar** [comment]
I am also having same issue its take forever to detect connection change(i.e when i switch wifi connections from one to another). is there any update regarding the topic.

**Comment by ydvsailendar** [comment]
> I am also having same issue its take forever to detect connection change(i.e when i switch wifi connections from one to another). is there any update regarding the topic.

so in my case i was getting this issue while switching the wifi networks and using the simmulateNetworkFailure() function helped.

**Comment by graebm** [comment]
You can configure your MQTT client to detect offline events more quickly using the `keepalive` option. This causes the client to send a PING to the server every `keepalive` seconds, and to assume it's been disconnected if it gets no response within `keepalive * 2` seconds. The default `keepalive` is 300 seconds (5 minutes), so try something lower. I ran some local tests and found issues with the disconnect-detection unless I also used the `reschedulePings: false` option.

Try using these
```deviceModule({..., keepalive: 10, reschedulePings: false})```
