### ISSUE TITLE
Error when unsubscribing from a topic

### ISSUE THREAD

**Issue by lxwbr** [aws/aws-iot-device-sdk-js#326]
Using `2.2.4` version and trying to unsubscribe on a topic:
```
return new Promise<Granted[]>((resolve, reject) => {
  client.unsubscribe(topic, { qos: 1 }, (err, granted) => {
    if (err) {
      reject(err)
    } else {
      resolve(granted)
    }
  })
})
```
will throw following error:
```
Uncaught TypeError: cb is not a function
      at MqttClient._handleAck (node_modules/mqtt/lib/client.js:1062:7)
      at MqttClient._handlePacket (node_modules/mqtt/lib/client.js:343:12)
      at work (node_modules/mqtt/lib/client.js:292:12)
      at Writable.writable._write (node_modules/mqtt/lib/client.js:302:5)
      at doWrite (node_modules/readable-stream/lib/_stream_writable.js:428:64)
      at writeOrBuffer (node_modules/readable-stream/lib/_stream_writable.js:417:5)
      at Writable.write (node_modules/readable-stream/lib/_stream_writable.js:334:11)
      at Duplexify.ondata (node_modules/readable-stream/lib/_stream_readable.js:619:20)
      at Duplexify.EventEmitter.emit (domain.js:482:12)
      at addChunk (node_modules/readable-stream/lib/_stream_readable.js:291:12)
      at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Duplexify.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at Duplexify._forward (node_modules/duplexify/index.js:170:26)
      at Transform.onreadable (node_modules/duplexify/index.js:134:10)
      at Transform.EventEmitter.emit (domain.js:482:12)
      at emitReadable_ (node_modules/readable-stream/lib/_stream_readable.js:504:10)
      at emitReadable (node_modules/readable-stream/lib/_stream_readable.js:498:62)
      at addChunk (node_modules/readable-stream/lib/_stream_readable.js:298:29)
      at readableAddChunk (node_modules/readable-stream/lib/_stream_readable.js:278:11)
      at Transform.Readable.push (node_modules/readable-stream/lib/_stream_readable.js:245:10)
      at Transform.push (node_modules/readable-stream/lib/_stream_transform.js:148:32)
      at WebSocket.onmessage (node_modules/websocket-stream/stream.js:167:11)
      at WebSocket.onMessage (node_modules/websocket-stream/node_modules/ws/lib/EventTarget.js:99:16)
      at WebSocket.EventEmitter.emit (domain.js:482:12)
      at Receiver._receiver.onmessage (node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:141:47)
      at Receiver.dataMessage (node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:380:14)
      at Receiver.getData (node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:330:12)
      at Receiver.startLoop (node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:165:16)
      at Receiver.add (node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:139:10)
      at TLSSocket.<anonymous> (node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:138:22)
      at TLSSocket.EventEmitter.emit (domain.js:482:12)
      at addChunk (_stream_readable.js:294:12)
      at readableAddChunk (_stream_readable.js:275:11)
      at TLSSocket.Readable.push (_stream_readable.js:209:10)
      at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
```
Is this a known issue or am I doing something wrong?

**Comment by ShunKeJiang** [comment]
@lxwbr If it's a thing it doesn't seem to have a {qos:1} parameter

**Comment by jmklix** [comment]
If you are still getting this error please open a new issue with the following info:

**Describe the bug**
A clear and concise description of what the bug is.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Additional context**
Add any other context about the problem here.
