### ISSUE TITLE
How to get request from AWS IOT core shadow to JS

### ISSUE THREAD

**Issue by amandugar** [aws/aws-iot-device-sdk-js#336]
I am able to publish request to node js but I am not able to get request from aws iot core shadow if someone can help me out with this

**Comment by rccarper** [comment]
Hello, are you hitting a specific problem, and are there any error logs and/or sample code that you are able to share?  Also, our "temperature-control" example makes use of shadows and may be helpful: https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/temperature-control/temperature-control.js

**Comment by amandugar** [comment]
Basically I want to publish something from AWS IOT core to node js can you help me with it

**Comment by amandugar** [comment]
TypeError: thingsShadow.get is not a function
    at DeviceClient.<anonymous> (G:\arduino-node\arduino-node-final\app.js:36:36)
    at DeviceClient.emit (events.js:315:20)
    at MqttClient.<anonymous> (G:\arduino-node\arduino-node-final\node_modules\aws-iot-device-sdk\device\index.js:769:12)
    at MqttClient.emit (events.js:327:22)
    at MqttClient._handleConnack (G:\arduino-node\arduino-node-final\node_modules\mqtt\lib\client.js:918:10)
    at MqttClient._handlePacket (G:\arduino-node\arduino-node-final\node_modules\mqtt\lib\client.js:350:12)
    at work (G:\arduino-node\arduino-node-final\node_modules\mqtt\lib\client.js:292:12)
    at Writable.writable._write (G:\arduino-node\arduino-node-final\node_modules\mqtt\lib\client.js:302:5)
    at doWrite (G:\arduino-node\arduino-node-final\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (G:\arduino-node\arduino-node-final\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at Writable.write (G:\arduino-node\arduino-node-final\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at TLSSocket.ondata (_stream_readable.js:717:22)
    at TLSSocket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at TLSSocket.Readable.push (_stream_readable.js:212:10)

**Comment by rccarper** [comment]
Sorry for the delay in response.  It sounds the shadow functionality may not be being imported correctly.  Are you importing "thingShadow" using a require statement, and then instantiating "thingsShadow" with that?  If so, would you be able to post those couple lines of code?
