### ISSUE TITLE
'Forbidden' Message when updating thing shadow

### ISSUE THREAD

**Issue by bryanyuchen** [aws/aws-iot-device-sdk-js#70]
while trying out the code from a previous issue:

https://github.com/aws/aws-iot-device-sdk-js/issues/22

I get this error:

START RequestId: a6c5092c-3f16-11e6-97ec-d132fdbb08b2 Version: $LATEST
2016-06-30T23:02:01.596Z	a6c5092c-3f16-11e6-97ec-d132fdbb08b2	{ [ForbiddenException: Forbidden]
  message: 'Forbidden',
  code: 'ForbiddenException',
  time: Thu Jun 30 2016 23:02:01 GMT+0000 (UTC),
  requestId: 'c41c2360-084a-45ac-9a1c-a89890c43198',
  statusCode: 403,
  retryable: false,
  retryDelay: 14.996524062007666 } 'ForbiddenException: Forbidden
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:43:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:615:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:617:12)'
END RequestId: a6c5092c-3f16-11e6-97ec-d132fdbb08b2
REPORT RequestId: a6c5092c-3f16-11e6-97ec-d132fdbb08b2	Duration: 1330.53 ms	Billed Duration: 1400 ms 	Memory Size: 128 MB	Max Memory Used: 26 MB	

could you please let me know where I went wrong?
thanks

**Comment by bhadrip** [comment]
Hello @bryanyuchen,

Can you share the attached policy to the role that is used to execute the Lambda function ? Role name can be found in the `configuration` tab of the lambda function. 

More information on AWS IoT policies can be found [here] (http://docs.aws.amazon.com/iot/latest/developerguide/authorization.html)


Thanks
Bhadri

**Comment by bryanyuchen** [comment]
Hi @bhadrip,

right now the role is "lambda_basic_execution",

policy is:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "arn:aws:logs:*:*:*"
    }
  ]
}

Thanks!

**Comment by bryanyuchen** [comment]
Hey @bhadrip 

I played around with the policy to allow access and it worked out! 
Thanks!

**Comment by bhadrip** [comment]
Thats great !

Thanks for using AWS IoT.

**Comment by kgowru** [comment]
@bryanyuchen what policies did you add to get this to work?

**Comment by bryanyuchen** [comment]
Hey kgowru,

try attaching the 'AWSIoTFullAccess' policy to your IAM role. If you can't find it, here is what the policy looks like:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:*"
            ],
            "Resource": "*"
       }
    ]
}
