### ISSUE TITLE
TypeError: awsIot.thingshadow is not a function

### ISSUE THREAD

**Issue by glidenz** [aws/aws-iot-device-sdk-js#90]
Hi All

VERY new to node.js and development in general to be truthful. I've starting playing around with node.js and aws-iot-device-sdk. 

I've got a few test apps up and running performing some very simple sub and pub on topics etc etc. That was using the device part of the sdk

var device = awsIot.device({

Now when I want to test some Device Shadow stuff as per the sdk sample code I swap over to

var thingshadows = awsIot.thingshadow({

But I get the below error. Any ideas why thingshadow is not working?

/Users/marklloyd/Documents/workspace/AWS_NODE_TEST/AWS_NODE_TEST.js:14
var thingshadows = awsIot.thingshadow({
                          ^

TypeError: awsIot.thingshadow is not a function
    at Object.<anonymous> (/Users/marklloyd/Documents/workspace/AWS_NODE_TEST/AWS_NODE_TEST.js:14:27)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by glidenz** [comment]
I think I have it sorted. My bad at this point
